# Generated by Django 5.1.4 on 2024-12-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imtiaz', '0002_category_product_featureproductimage_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='most_wanted',
            field=models.BooleanField(default=False),
        ),
    ]
