# Generated by Django 5.1.4 on 2025-01-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imtiaz', '0004_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
