# Generated by Django 5.1.4 on 2025-01-01 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imtiaz', '0006_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featureproductimage',
            name='image',
        ),
        migrations.AddField(
            model_name='featureproductimage',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='feature_product_images/'),
        ),
        migrations.AddField(
            model_name='featureproductimage',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='feature_product_images/'),
        ),
        migrations.AddField(
            model_name='featureproductimage',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='feature_product_images/'),
        ),
        migrations.AlterField(
            model_name='featureproductimage',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature_product_images', to='imtiaz.product'),
        ),
    ]
