# Generated by Django 5.1.4 on 2025-01-01 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imtiaz', '0007_remove_featureproductimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureproductimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_product_images', to='imtiaz.product'),
        ),
    ]
