# Generated by Django 5.1.4 on 2025-01-01 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imtiaz', '0008_alter_featureproductimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureproductimage',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature_product_images', to='imtiaz.product'),
        ),
    ]
